app = "stock-alert-bot-quanpink"
primary_region = "sin"

[build]

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1