app = 'stock-alert-bot'
primary_region = 'sin'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = 512
  cpu_kind = "shared"
  cpus = 1