app = 'stock-alert-bot'
primary_region = 'sin'

[build]

[env]
  PORT = '8080'

[mounts]
  source = "stock_bot_data"
  destination = "/data"
  initial_size = "1gb"

[[vm]]
  memory = 512
  cpu_kind = "shared"
  cpus = 1